<script setup lang="ts">
import { ArrowLeft, Building2, CheckCircle2, History, MapPin, Star } from 'lucide-vue-next'
import ContractorGeneralTab from '~/components/contractors/ContractorGeneralTab.vue'
import ContractorOrganizationsTab from '~/components/contractors/ContractorOrganizationsTab.vue'
import ContractorLocationsTab from '~/components/contractors/ContractorLocationsTab.vue'
import ContractorVisitsTab from '~/components/contractors/ContractorVisitsTab.vue'
definePageMeta({ layout: 'default' })
const route=useRoute()
const tenantId=computed(()=>String(route.params.tenantId??'1'))
const contractorId=computed(()=>Number(Array.isArray(route.params.contractorId)?route.params.contractorId[0]:route.params.contractorId??1))
type Contractor={id:number;name:string;shortName:string;type:'Daimi'|'Geçici';status:'active'|'passive';rating:number;reviewCount:number}
const contractors:Contractor[]=[{id:1,name:'ISS Tesis Yönetim Hizmetleri A.Ş.',shortName:'ISS',type:'Daimi',status:'active',rating:4.5,reviewCount:300},{id:2,name:'Tepe Savunma ve Güvenlik Sistemleri A.Ş.',shortName:'Tepe',type:'Daimi',status:'active',rating:4.2,reviewCount:186},{id:3,name:'Sofra Yemek Üretim ve Hizmet A.Ş.',shortName:'Sofra',type:'Daimi',status:'active',rating:4.7,reviewCount:241},{id:4,name:'Bantaş Temizlik Hizmetleri Ltd. Şti.',shortName:'Bantaş',type:'Geçici',status:'active',rating:4.1,reviewCount:74},{id:5,name:'ABC Teknik Bakım Hizmetleri Ltd. Şti.',shortName:'ABC Teknik',type:'Geçici',status:'active',rating:4.6,reviewCount:38},{id:6,name:'Protek Güvenlik Hizmetleri A.Ş.',shortName:'Protek',type:'Daimi',status:'passive',rating:3.8,reviewCount:129},{id:7,name:'CleanPro Endüstriyel Temizlik A.Ş.',shortName:'CleanPro',type:'Geçici',status:'active',rating:4.3,reviewCount:52},{id:8,name:'Güven Plus Özel Güvenlik Ltd. Şti.',shortName:'Güven Plus',type:'Daimi',status:'active',rating:4.4,reviewCount:167},{id:9,name:'Lezzet Catering Hizmetleri A.Ş.',shortName:'Lezzet',type:'Geçici',status:'active',rating:4.8,reviewCount:91},{id:10,name:'TeknikServis Bakım ve Onarım A.Ş.',shortName:'TeknikServis',type:'Daimi',status:'active',rating:4,reviewCount:113},{id:11,name:'Hijyen Profesyonel Temizlik Ltd. Şti.',shortName:'Hijyen',type:'Daimi',status:'passive',rating:3.9,reviewCount:68},{id:12,name:'Anadolu Personel Destek Hizmetleri A.Ş.',shortName:'Anadolu',type:'Geçici',status:'active',rating:4.5,reviewCount:47}]
const contractor=computed(()=>contractors.find(x=>x.id===contractorId.value)??contractors[0])
const isTemporary=computed(()=>contractor.value.type==='Geçici' || [4,5,7,9,12].includes(contractorId.value))
const statusText=computed(()=>contractor.value.status==='active'?'Aktif':'Pasif')
const activeTab=ref('general')
const tabs=computed(()=>[
  {key:'general',label:'Genel Bilgiler',icon:Building2},
  {key:'organizations',label:'Organizasyon İlişkileri',icon:Building2},
  ...(isTemporary.value ? [{key:'visits',label:'Saha Ziyaretleri',icon:History}] : [{key:'locations',label:'Lokasyonlar',icon:MapPin}])
])
const organizations=computed(()=>isTemporary.value?[{name:'Medikal Grubu',status:'Aktif',start:'01.03.2026',end:'15.03.2026',list:'Beyaz Liste'},{name:'Arçelik Grubu',status:'Aktif',start:'10.07.2026',end:'10.08.2026',list:'Beyaz Liste'}]:[{name:'Medikal Grubu',status:'Aktif',start:'01.01.2026',end:'31.12.2026',list:'Beyaz Liste'},{name:'Otomotiv Grubu',status:'Pasif',start:'01.01.2025',end:'31.12.2025',list:'Tanımlı değil'},{name:'Dayanıklı Tüketim Grubu',status:'Kara Liste',start:'01.06.2026',end:'01.06.2036',list:'Kara Liste'}])
const locations=[{name:'Beylikdüzü Kampüsü',business:'Arçelik A.Ş.',status:'Aktif'},{name:'Sütlüce Kampüsü',business:'Arçelik Pazarlama A.Ş.',status:'Aktif'},{name:'Çayırova Fabrikası',business:'Beko Europe',status:'Pasif'}]
const visits=[
  {date:'26.08.2026',location:'Beylikdüzü Kampüsü',business:'Arçelik A.Ş.',purpose:'Planlı ekipman kontrolü',people:4,status:'Planlanan'},
  {date:'24.08.2026',location:'Çayırova Fabrikası',business:'Arçelik A.Ş.',purpose:'Teknik bakım ve saha çalışması',people:3,status:'Devam Ediyor'},
  {date:'18.08.2026',location:'Beylikdüzü Kampüsü',business:'Arçelik A.Ş.',purpose:'Forklift bakım ve teknik servis',people:3,status:'Tamamlandı'},
  {date:'04.07.2026',location:'Çayırova Fabrikası',business:'Arçelik A.Ş.',purpose:'Periyodik bakım',people:2,status:'Tamamlandı'},
  {date:'22.05.2026',location:'Sütlüce Kampüsü',business:'Arçelik Pazarlama A.Ş.',purpose:'Acil teknik müdahale',people:4,status:'Tamamlandı'},
  {date:'11.03.2026',location:'Beylikdüzü Kampüsü',business:'Arçelik A.Ş.',purpose:'Makine arıza müdahalesi',people:2,status:'Tamamlandı'}
]
const tabContractor=computed(()=>({...contractor.value,statusText:statusText.value}))
const temporaryHistoryUrl=computed(()=>`/tenants/${tenantId.value}/contractors/${contractorId.value}/temporary-history`)
</script>
<template><div class="font-outfit mx-auto w-full max-w-[1400px]">
<div class="mb-6 flex items-start gap-4"><NuxtLink :to="`/tenants/${tenantId}/contractors/`" class="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-500 hover:bg-gray-50"><ArrowLeft :size="17" /></NuxtLink><div><div class="flex flex-wrap items-center gap-2"><h1 class="text-2xl font-semibold tracking-tight text-gray-900">{{ contractor.name }}</h1><span class="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-medium text-brand-600">{{ contractor.shortName }}</span><span class="rounded-full px-2.5 py-1 text-xs font-medium" :class="isTemporary?'bg-amber-50 text-amber-600':'bg-success-50 text-success-600'">{{ contractor.type }}</span></div><p class="mt-1.5 text-sm text-gray-500">Alt yüklenici detayları, organizasyon ilişkileri ve saha geçmişi.</p></div></div>
<div class="mb-5 grid grid-cols-1 gap-4 lg:grid-cols-4"><section class="rounded-xl border border-gray-200 bg-white p-5 shadow-theme-xs lg:col-span-3"><div class="flex items-center gap-4"><div class="flex h-12 w-12 items-center justify-center rounded-full bg-brand-50 text-sm font-bold text-brand-600">{{ contractor.shortName.slice(0,2).toUpperCase() }}</div><div><p class="text-xs text-gray-500">Genel değerlendirme</p><div class="mt-1 flex items-center gap-2"><span class="text-2xl font-semibold text-gray-900">{{ contractor.rating.toFixed(1).replace('.', ',') }}</span><div class="flex items-center gap-0.5"><Star v-for="n in 5" :key="n" :size="16" :class="n <= Math.round(contractor.rating) ? 'fill-amber-400 text-amber-400' : 'text-gray-300'" /></div></div><p class="mt-1 text-xs text-gray-500">{{ contractor.reviewCount.toLocaleString('tr-TR') }} değerlendirme</p></div><div class="ml-auto hidden text-right sm:block"><p class="text-xs text-gray-500">Son değerlendirme</p><p class="mt-1 text-sm font-medium text-gray-800">4,5 / 5</p><p class="mt-1 text-[11px] text-gray-400">Son 12 ay</p></div></div></section><section class="rounded-xl border border-gray-200 bg-white p-5 shadow-theme-xs"><p class="text-xs text-gray-500">Durum</p><div class="mt-2 flex items-center gap-2"><CheckCircle2 :size="18" class="text-success-500"/><span class="text-sm font-semibold">{{ statusText }}</span></div><p class="mt-3 text-xs text-gray-500">{{ organizations.length }} organizasyon eşleşmesi</p></section></div>
<div v-if="isTemporary" class="mb-5 flex items-center justify-between rounded-xl border border-amber-200 bg-amber-50/60 px-5 py-4"><div class="flex items-center gap-3"><History :size="18" class="text-amber-600"/><div><p class="text-sm font-semibold text-amber-800">Geçici Alt Yüklenici</p><p class="mt-1 text-xs text-amber-700/80">Fiili saha ziyaretleri bu firma için ayrıca takip edilir.</p></div></div><NuxtLink :to="temporaryHistoryUrl" class="rounded-lg bg-amber-500 px-3 py-2 text-xs font-semibold text-white">Tüm Ziyaretleri Gör</NuxtLink></div>
<div class="mb-5 overflow-x-auto rounded-xl border border-gray-200 bg-white shadow-theme-xs"><div class="flex min-w-max items-center px-2"><button v-for="tab in tabs" :key="tab.key" type="button" class="group relative flex items-center gap-2 px-4 py-4 text-sm font-medium transition-colors" :class="activeTab===tab.key?'text-brand-600':'text-gray-500 hover:text-gray-800'" @click="activeTab=tab.key"><component :is="tab.icon" :size="16"/><span>{{ tab.label }}</span><span v-if="activeTab===tab.key" class="absolute inset-x-3 bottom-0 h-0.5 rounded-full bg-brand-500"></span></button></div></div>
<ContractorGeneralTab v-if="activeTab==='general'" :contractor="tabContractor" />
<ContractorOrganizationsTab v-else-if="activeTab==='organizations'" :organizations="organizations" />
<ContractorLocationsTab v-else-if="activeTab==='locations'" :locations="locations" />
<ContractorVisitsTab v-else-if="activeTab==='visits'" :visits="visits" :history-url="temporaryHistoryUrl" />
</div></template>