<script setup lang="ts">
import { ArrowLeft, Building2, CheckCircle2, MapPin, ShieldAlert, History, ClipboardCheck, Star, FileText } from 'lucide-vue-next'
definePageMeta({ layout: 'default' })
const route = useRoute()
const tenantId = computed(() => String(route.params.tenantId ?? '1'))
const contractorId = computed(() => Number(route.params.contractorId ?? 1))
type Contractor = { id:number; name:string; shortName:string; type:'Daimi'|'Geçici'; status:'active'|'passive'; rating:number; reviewCount:number }
const contractors: Contractor[] = [{id:1,name:'ISS Tesis Yönetim Hizmetleri A.Ş.',shortName:'ISS',type:'Daimi',status:'active',rating:4.5,reviewCount:300},{id:2,name:'Tepe Savunma ve Güvenlik Sistemleri A.Ş.',shortName:'Tepe',type:'Daimi',status:'active',rating:4.2,reviewCount:186},{id:3,name:'Sofra Yemek Üretim ve Hizmet A.Ş.',shortName:'Sofra',type:'Daimi',status:'active',rating:4.7,reviewCount:241},{id:4,name:'Bantaş Temizlik Hizmetleri Ltd. Şti.',shortName:'Bantaş',type:'Geçici',status:'active',rating:4.1,reviewCount:74},{id:5,name:'ABC Teknik Bakım Hizmetleri Ltd. Şti.',shortName:'ABC Teknik',type:'Geçici',status:'active',rating:4.6,reviewCount:38},{id:6,name:'Protek Güvenlik Hizmetleri A.Ş.',shortName:'Protek',type:'Daimi',status:'passive',rating:3.8,reviewCount:129},{id:7,name:'CleanPro Endüstriyel Temizlik A.Ş.',shortName:'CleanPro',type:'Geçici',status:'active',rating:4.3,reviewCount:52},{id:8,name:'Güven Plus Özel Güvenlik Ltd. Şti.',shortName:'Güven Plus',type:'Daimi',status:'active',rating:4.4,reviewCount:167},{id:9,name:'Lezzet Catering Hizmetleri A.Ş.',shortName:'Lezzet',type:'Geçici',status:'active',rating:4.8,reviewCount:91},{id:10,name:'TeknikServis Bakım ve Onarım A.Ş.',shortName:'TeknikServis',type:'Daimi',status:'active',rating:4.0,reviewCount:113},{id:11,name:'Hijyen Profesyonel Temizlik Ltd. Şti.',shortName:'Hijyen',type:'Daimi',status:'passive',rating:3.9,reviewCount:68},{id:12,name:'Anadolu Personel Destek Hizmetleri A.Ş.',shortName:'Anadolu',type:'Geçici',status:'active',rating:4.5,reviewCount:47}]
const contractor = computed(() => contractors.find(x => x.id === contractorId.value) ?? contractors[0])
const isTemporary = computed(() => contractor.value.type === 'Geçici')
const statusText = computed(() => contractor.value.status === 'active' ? 'Aktif' : 'Pasif')
const ratingText = computed(() => contractor.value.rating.toFixed(1).replace('.', ','))
const activeTab = ref('general')
const tabs = computed(() => [{key:'general',label:'Genel Bilgiler',icon:FileText},{key:'organizations',label:'Organizasyon İlişkileri',icon:Building2},{key:isTemporary.value?'visits':'locations',label:isTemporary.value?'Saha Ziyaretleri':'Lokasyonlar',icon:isTemporary.value?History:MapPin},{key:'history',label:'Çalışma Geçmişi',icon:History}])
const organizations = computed(() => isTemporary.value ? [{name:'Medikal Grubu',status:'Aktif',start:'01.03.2026',end:'15.03.2026',list:'Beyaz Liste'},{name:'Arçelik Grubu',status:'Aktif',start:'10.07.2026',end:'10.08.2026',list:'Beyaz Liste'}] : [{name:'Medikal Grubu',status:'Aktif',start:'01.01.2026',end:'31.12.2026',list:'Beyaz Liste'},{name:'Otomotiv Grubu',status:'Pasif',start:'01.01.2025',end:'31.12.2025',list:'Tanımlı değil'},{name:'Dayanıklı Tüketim Grubu',status:'Kara Liste',start:'01.06.2026',end:'01.06.2036',list:'Kara Liste'}])
const locations = [{name:'Beylikdüzü Kampüsü',business:'Arçelik A.Ş.',status:'Aktif'},{name:'Sütlüce Kampüsü',business:'Arçelik Pazarlama A.Ş.',status:'Aktif'},{name:'Çayırova Fabrikası',business:'Beko Europe',status:'Pasif'}]
const visits = [{date:'18.08.2026',location:'Beylikdüzü Kampüsü',business:'Arçelik A.Ş.',purpose:'Forklift bakım ve teknik servis',people:3,status:'Tamamlandı'},{date:'04.07.2026',location:'Çayırova Fabrikası',business:'Arçelik A.Ş.',purpose:'Periyodik bakım',people:2,status:'Tamamlandı'},{date:'22.05.2026',location:'Sütlüce Kampüsü',business:'Arçelik Pazarlama A.Ş.',purpose:'Acil teknik müdahale',people:4,status:'Tamamlandı'},{date:'11.03.2026',location:'Beylikdüzü Kampüsü',business:'Arçelik A.Ş.',purpose:'Makine arıza müdahalesi',people:2,status:'Tamamlandı'}]
const history = computed(() => organizations.value.map((x,i) => ({year:i===0?'2026':'2025',organization:x.name,status:x.status,contract:`${x.start} – ${x.end}`})))
const temporaryHistoryUrl = computed(() => `/tenants/${tenantId.value}/contractors/${contractorId.value}/temporary-history`)
</script>
<template><div class="font-outfit mx-auto w-full max-w-[1400px]">
<div class="mb-6 flex items-start gap-4"><NuxtLink :to="`/tenants/${tenantId}/contractors/`" class="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-500 hover:bg-gray-50"><ArrowLeft :size="17" /></NuxtLink><div><div class="flex flex-wrap items-center gap-2"><h1 class="text-2xl font-semibold tracking-tight text-gray-900">{{ contractor.name }}</h1><span class="rounded-full bg-brand-50 px-2.5 py-1 text-xs font-medium text-brand-600">{{ contractor.shortName }}</span><span class="rounded-full px-2.5 py-1 text-xs font-medium" :class="isTemporary?'bg-amber-50 text-amber-600':'bg-success-50 text-success-600'">{{ contractor.type }}</span></div><p class="mt-1.5 text-sm text-gray-500">Alt yüklenici detayları, organizasyon ilişkileri ve çalışma geçmişi.</p></div></div>
<div class="mb-5 grid grid-cols-1 gap-4 lg:grid-cols-4"><section class="rounded-xl border border-gray-200 bg-white p-5 shadow-theme-xs lg:col-span-3"><div class="flex items-center gap-4"><div class="flex h-12 w-12 items-center justify-center rounded-full bg-brand-50 text-sm font-bold text-brand-600">{{ contractor.shortName.slice(0,2).toUpperCase() }}</div><div><p class="text-xs text-gray-500">Genel değerlendirme</p><div class="mt-1 flex items-center gap-2"><span class="text-2xl font-semibold text-gray-900">{{ ratingText }}</span><div class="flex items-center gap-0.5"><Star v-for="n in 5" :key="n" :size="16" :class="n <= Math.round(contractor.rating) ? 'fill-amber-400 text-amber-400' : 'text-gray-300'" /></div></div><p class="mt-1 text-xs text-gray-500">{{ contractor.reviewCount.toLocaleString('tr-TR') }} değerlendirme</p></div><div class="ml-auto hidden text-right sm:block"><p class="text-xs text-gray-500">Son değerlendirme</p><p class="mt-1 text-sm font-medium text-gray-800">4,5 / 5</p><p class="mt-1 text-[11px] text-gray-400">Son 12 ay</p></div></div></section><section class="rounded-xl border border-gray-200 bg-white p-5 shadow-theme-xs"><p class="text-xs text-gray-500">Durum</p><div class="mt-2 flex items-center gap-2"><CheckCircle2 :size="18" class="text-success-500"/><span class="text-sm font-semibold">{{ statusText }}</span></div><p class="mt-3 text-xs text-gray-500">{{ organizations.length }} organizasyon eşleşmesi</p></section></div>
<div v-if="isTemporary" class="mb-5 flex items-center justify-between rounded-xl border border-amber-200 bg-amber-50/60 px-5 py-4"><div class="flex items-center gap-3"><History :size="18" class="text-amber-600"/><div><p class="text-sm font-semibold text-amber-800">Geçici Alt Yüklenici</p><p class="mt-1 text-xs text-amber-700/80">Fiili saha ziyaretleri bu firma için ayrıca takip edilir.</p></div></div><NuxtLink :to="temporaryHistoryUrl" class="rounded-lg bg-amber-500 px-3 py-2 text-xs font-semibold text-white">Tüm Ziyaretleri Gör</NuxtLink></div>
<div class="mb-5 overflow-x-auto rounded-xl border border-gray-200 bg-white shadow-theme-xs"><div class="flex min-w-max items-center px-2"><button v-for="tab in tabs" :key="tab.key" type="button" class="group relative flex items-center gap-2 px-4 py-4 text-sm font-medium transition-colors" :class="activeTab===tab.key?'text-brand-600':'text-gray-500 hover:text-gray-800'" @click="activeTab=tab.key"><component :is="tab.icon" :size="16"/><span>{{ tab.label }}</span><span v-if="activeTab===tab.key" class="absolute inset-x-3 bottom-0 h-0.5 rounded-full bg-brand-500"></span></button></div></div>
<section v-if="activeTab==='general'" class="rounded-xl border border-gray-200 bg-white p-6 shadow-theme-xs"><div class="mb-6 flex items-center justify-between"><div><h2 class="text-sm font-semibold text-gray-900">Genel Bilgiler</h2><p class="mt-1 text-xs text-gray-500">Merkezi havuzdaki firma kaydı.</p></div><button class="h-9 rounded-lg border border-gray-200 px-3 text-xs font-medium">Düzenle</button></div><div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4"><div><span class="text-xs text-gray-500">Firma Unvanı</span><p class="mt-1 text-sm font-medium text-gray-800">{{ contractor.name }}</p></div><div><span class="text-xs text-gray-500">Kısa Ad</span><p class="mt-1 text-sm font-medium text-gray-800">{{ contractor.shortName }}</p></div><div><span class="text-xs text-gray-500">Tür</span><p class="mt-1 text-sm font-medium text-gray-800">{{ contractor.type }}</p></div><div><span class="text-xs text-gray-500">Durum</span><p class="mt-1 text-sm font-medium text-gray-800">{{ statusText }}</p></div></div><div class="mt-8 border-t border-gray-100 pt-6"><h3 class="text-sm font-semibold text-gray-900">Değerlendirme Özeti</h3><div class="mt-4 flex items-center gap-4"><span class="text-3xl font-semibold">{{ ratingText }}</span><div><div class="flex gap-0.5"><Star v-for="n in 5" :key="n" :size="17" :class="n <= Math.round(contractor.rating) ? 'fill-amber-400 text-amber-400' : 'text-gray-300'" /></div><p class="mt-1 text-xs text-gray-500">{{ contractor.reviewCount.toLocaleString('tr-TR') }} değerlendirme</p></div></div></div></section>
<section v-else-if="activeTab==='organizations'" class="rounded-xl border border-gray-200 bg-white p-6 shadow-theme-xs"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-sm font-semibold text-gray-900">Organizasyon İlişkileri</h2><p class="mt-1 text-xs text-gray-500">Bu firma için tenant içindeki organizasyon ilişkileri.</p></div><button class="h-9 rounded-lg bg-brand-500 px-3 text-xs font-semibold text-white">Organizasyon Ekle</button></div><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left"><thead><tr class="border-b border-gray-100 text-xs text-gray-500"><th class="pb-3 font-medium">Organizasyon</th><th class="pb-3 font-medium">Durum</th><th class="pb-3 font-medium">Çalışma Dönemi</th><th class="pb-3 font-medium">Liste Durumu</th></tr></thead><tbody><tr v-for="item in organizations" :key="item.name" class="border-b border-gray-100 last:border-0"><td class="py-4 text-sm font-medium text-gray-800">{{ item.name }}</td><td class="py-4"><span class="rounded-full px-2 py-1 text-[11px] font-medium" :class="item.status==='Aktif'?'bg-success-50 text-success-600':'bg-gray-100 text-gray-500'">{{ item.status }}</span></td><td class="py-4 text-xs text-gray-500">{{ item.start }} – {{ item.end }}</td><td class="py-4"><span class="text-xs font-medium" :class="item.list==='Kara Liste'?'text-error-600':'text-gray-600'">{{ item.list }}</span></td></tr></tbody></table></div></section>
<section v-else-if="activeTab==='locations'" class="rounded-xl border border-gray-200 bg-white p-6 shadow-theme-xs"><div class="mb-5"><h2 class="text-sm font-semibold text-gray-900">Lokasyonlar</h2><p class="mt-1 text-xs text-gray-500">Daimi alt yüklenicinin lokasyon bazındaki ilişkileri.</p></div><div class="grid grid-cols-1 gap-4 md:grid-cols-2 lg:grid-cols-3"><div v-for="item in locations" :key="item.name" class="rounded-xl border border-gray-100 p-5"><div class="flex items-start justify-between gap-3"><div><p class="text-sm font-medium text-gray-800">{{ item.name }}</p><p class="mt-1 text-xs text-gray-500">{{ item.business }}</p></div><MapPin :size="17" class="text-gray-400"/></div><span class="mt-4 inline-block rounded-full bg-success-50 px-2.5 py-1 text-[11px] font-medium text-success-600">{{ item.status }}</span></div></div></section>
<section v-else-if="activeTab==='visits'" class="rounded-xl border border-gray-200 bg-white p-6 shadow-theme-xs"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-sm font-semibold text-gray-900">Saha Ziyaret Geçmişi</h2><p class="mt-1 text-xs text-gray-500">Geçici alt yüklenicinin fiili saha ziyaretleri.</p></div><NuxtLink :to="temporaryHistoryUrl" class="text-xs font-medium text-brand-500">Tümünü Gör</NuxtLink></div><div class="overflow-x-auto"><table class="w-full min-w-[900px] text-left"><thead><tr class="border-b border-gray-100 text-xs text-gray-500"><th class="pb-3 font-medium">Tarih</th><th class="pb-3 font-medium">Lokasyon</th><th class="pb-3 font-medium">Ana Firma</th><th class="pb-3 font-medium">Ziyaret Nedeni</th><th class="pb-3 font-medium">Personel</th><th class="pb-3 font-medium">Durum</th></tr></thead><tbody><tr v-for="visit in visits" :key="visit.date+visit.location" class="border-b border-gray-100 last:border-0"><td class="py-4 text-sm font-medium text-gray-800">{{ visit.date }}</td><td class="py-4 text-sm">{{ visit.location }}</td><td class="py-4 text-xs text-gray-500">{{ visit.business }}</td><td class="py-4 text-sm text-gray-600">{{ visit.purpose }}</td><td class="py-4 text-sm">{{ visit.people }}</td><td class="py-4"><span class="inline-flex items-center gap-1.5 rounded-full bg-success-50 px-2.5 py-1 text-xs font-medium text-success-600"><ClipboardCheck :size="13"/>{{ visit.status }}</span></td></tr></tbody></table></div></section>
<section v-else class="rounded-xl border border-gray-200 bg-white p-6 shadow-theme-xs"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-sm font-semibold text-gray-900">Çalışma Geçmişi</h2><p class="mt-1 text-xs text-gray-500">Organizasyon bazındaki geçmiş çalışma dönemleri ve sözleşmeler.</p></div><button class="h-9 rounded-lg border border-gray-200 px-3 text-xs font-medium">Yeni Kayıt</button></div><div class="overflow-x-auto"><table class="w-full min-w-[700px] text-left"><thead><tr class="border-b border-gray-100 text-xs text-gray-500"><th class="pb-3 font-medium">Yıl</th><th class="pb-3 font-medium">Organizasyon</th><th class="pb-3 font-medium">Çalışma Dönemi</th><th class="pb-3 font-medium">Durum</th><th class="pb-3 font-medium">Sözleşme</th></tr></thead><tbody><tr v-for="item in history" :key="item.year+item.organization" class="border-b border-gray-100 last:border-0"><td class="py-4 text-sm font-medium">{{ item.year }}</td><td class="py-4 text-sm">{{ item.organization }}</td><td class="py-4 text-xs text-gray-500">{{ item.contract }}</td><td class="py-4"><span class="rounded-full bg-success-50 px-2 py-1 text-[11px] font-medium text-success-600">{{ item.status }}</span></td><td class="py-4"><button class="text-xs font-medium text-brand-500">Görüntüle</button></td></tr></tbody></table></div><div class="mt-6 rounded-xl border border-error-200 bg-error-50/40 p-4"><div class="flex items-start gap-3"><ShieldAlert :size="18" class="mt-0.5 text-error-600"/><div><p class="text-sm font-semibold text-error-700">Liste Durumu Uyarısı</p><p class="mt-1 text-xs text-error-700/80">Dayanıklı Tüketim Grubu için örnek kara liste kaydı bulunmaktadır.</p></div></div></div></section>
</div></div></template>