<script setup lang="ts">
import { ref } from 'vue'
import { ChevronDown } from 'lucide-vue-next'
type Visit = { date: string; location: string; business: string; purpose: string; people: number; status: string; personnel?: string[]; vehicles?: string[]; equipment?: string[]; chemicals?: string[] }
const props = defineProps<{ visits: Visit[] }>()
const expandedLogVisit = ref<string | null>(null)
const statusMeta = { Planlanan:{classes:'bg-brand-50 text-brand-600',dot:'bg-brand-500'},'Devam Ediyor':{classes:'bg-warning-50 text-warning-600',dot:'bg-warning-500'},Tamamlandı:{classes:'bg-success-50 text-success-600',dot:'bg-success-500'} } as const
const visitKey=(visit:Visit)=>`${visit.date}-${visit.location}-${visit.business}`
const visitLogs=(visit:Visit)=>[{date:`${visit.date} 09:15`,action:'Ziyaret tamamlandı',user:'Mehmet Kaya'},{date:`${visit.date} 08:40`,action:'Ziyaret onaylandı',user:'Mehmet Kaya'},{date:`${visit.date} 08:15`,action:'Saha ziyareti oluşturuldu',user:'Ahmet Yılmaz'}]
</script>
<template>
<div><div class="mb-6"><h2 class="text-sm font-semibold text-gray-900">İşlem Geçmişi</h2><p class="mt-1 text-xs text-gray-500">Her saha ziyareti için yapılan işlemler ve onay hareketleri.</p></div><div class="space-y-3"><div v-for="visit in props.visits" :key="visitKey(visit)" class="overflow-hidden rounded-xl border border-gray-100 bg-white"><button type="button" class="flex w-full items-center justify-between gap-4 p-4 text-left hover:bg-gray-50/70" @click="expandedLogVisit=expandedLogVisit===visitKey(visit)?null:visitKey(visit)"><div class="min-w-0"><div class="flex flex-wrap items-center gap-2"><span class="text-sm font-semibold text-gray-800">{{ visit.date }}</span><span class="text-xs text-gray-400">•</span><span class="text-xs text-gray-600">{{ visit.location }}</span><span class="rounded-full bg-gray-50 px-2 py-1 text-[10px] font-medium text-gray-500">{{ visit.business }}</span><span class="inline-flex items-center gap-1.5 rounded-full px-2.5 py-1 text-[10px] font-semibold" :class="statusMeta[visit.status as keyof typeof statusMeta]?.classes || 'bg-gray-100 text-gray-500'"><span class="h-1.5 w-1.5 rounded-full" :class="statusMeta[visit.status as keyof typeof statusMeta]?.dot || 'bg-gray-400'"></span>{{ visit.status }}</span></div><p class="mt-1 text-xs text-gray-500">{{ visit.purpose }}</p></div><ChevronDown :size="16" class="shrink-0 text-gray-400 transition-transform" :class="expandedLogVisit===visitKey(visit)?'rotate-180':''"/></button><div v-if="expandedLogVisit===visitKey(visit)" class="border-t border-gray-100 bg-gray-50/50 px-4 py-3"><div class="space-y-3"><div v-for="log in visitLogs(visit)" :key="log.date+log.action" class="flex items-center justify-between gap-4"><div class="flex items-center gap-3"><div class="h-2 w-2 rounded-full bg-brand-500"></div><div><p class="text-xs font-medium text-gray-700">{{ log.action }}</p><p class="mt-0.5 text-[11px] text-gray-400">{{ log.user }}</p></div></div><span class="shrink-0 text-[11px] text-gray-400">{{ log.date }}</span></div></div></div></div></div></div>
</template>