<script setup lang="ts">
import { Star } from 'lucide-vue-next'
type Evaluation={date:string;score:number;category:string;comment:string;organization:string}
defineProps<{ contractor: { name: string; shortName: string; type: string; statusText: string; rating: number; reviewCount: number }; evaluations?: Evaluation[] }>()
const evaluations=[{date:'18.08.2026',score:5,category:'Saha Performansı',comment:'Saha çalışması ve İSG kurallarına uyumu başarılı.',organization:'Medikal Grubu'},{date:'02.08.2026',score:4,category:'Hizmet Kalitesi',comment:'Hizmet kalitesi iyi, evrak süreçleri eksiksiz.',organization:'Arçelik Grubu'},{date:'14.07.2026',score:5,category:'İSG Uygunluğu',comment:'Saha ekibi gerekli PPE kullanımı ve kurallara uyum konusunda başarılı.',organization:'Medikal Grubu'},{date:'26.06.2026',score:4,category:'İş Disiplini',comment:'Planlanan çalışma zamanlarına uyum sağlandı.',organization:'Otomotiv Grubu'}]
</script>
<template>
<section class="rounded-xl border border-gray-200 bg-white p-6 shadow-theme-xs">
  <div class="mb-6 flex items-center justify-between"><div><h2 class="text-sm font-semibold text-gray-900">Genel Bilgiler</h2><p class="mt-1 text-xs text-gray-500">Merkezi havuzdaki firma kaydı.</p></div><button class="h-9 rounded-lg border border-gray-200 px-3 text-xs font-medium">Düzenle</button></div>
  <div class="grid grid-cols-1 gap-6 md:grid-cols-2 lg:grid-cols-4"><div><span class="text-xs text-gray-500">Firma Unvanı</span><p class="mt-1 text-sm font-medium text-gray-800">{{ contractor.name }}</p></div><div><span class="text-xs text-gray-500">Kısa Ad</span><p class="mt-1 text-sm font-medium text-gray-800">{{ contractor.shortName }}</p></div><div><span class="text-xs text-gray-500">Tür</span><p class="mt-1 text-sm font-medium text-gray-800">{{ contractor.type }}</p></div><div><span class="text-xs text-gray-500">Durum</span><p class="mt-1 text-sm font-medium text-gray-800">{{ contractor.statusText }}</p></div></div>
  <div class="mt-8 border-t border-gray-100 pt-6"><div class="flex items-center justify-between"><div><h3 class="text-sm font-semibold text-gray-900">Değerlendirme Özeti</h3><p class="mt-1 text-xs text-gray-500">Alt yüklenicinin son değerlendirmeleri.</p></div><div class="flex items-center gap-3"><span class="text-3xl font-semibold">{{ contractor.rating.toFixed(1).replace('.', ',') }}</span><div><div class="flex gap-0.5"><Star v-for="n in 5" :key="n" :size="17" :class="n <= Math.round(contractor.rating) ? 'fill-amber-400 text-amber-400' : 'text-gray-300'" /></div><p class="mt-1 text-xs text-gray-500">{{ contractor.reviewCount.toLocaleString('tr-TR') }} değerlendirme</p></div></div></div>
    <div class="mt-5 grid grid-cols-1 gap-3 lg:grid-cols-2"><article v-for="evaluation in evaluations" :key="evaluation.date+evaluation.organization" class="rounded-xl border border-gray-100 bg-gray-50/50 p-4"><div class="flex items-start justify-between gap-4"><div><div class="flex items-center gap-2"><span class="text-xs font-semibold text-gray-800">{{ evaluation.category }}</span><span class="text-[11px] text-gray-400">{{ evaluation.organization }}</span></div><div class="mt-1 flex gap-0.5"><Star v-for="n in 5" :key="n" :size="13" :class="n <= evaluation.score ? 'fill-amber-400 text-amber-400' : 'text-gray-300'" /></div></div><span class="text-[11px] text-gray-400">{{ evaluation.date }}</span></div><p class="mt-3 text-xs leading-5 text-gray-600">{{ evaluation.comment }}</p></article></div>
  </div>
</section>
</template>