<script setup lang="ts">
import { Check, X } from 'lucide-vue-next'
const props=defineProps<{ modelValue:boolean }>()
const emit=defineEmits<{ 'update:modelValue':[value:boolean]; save:[payload:{name:string;type:string;is_active:boolean}] }>()
const name=ref(''); const type=ref('facility'); const isActive=ref(true)
const types=[{value:'facility',label:'Tesis / Genel Alan'},{value:'production',label:'Üretim Alanı'},{value:'office',label:'İdari / Ofis'},{value:'warehouse',label:'Depo / Lojistik'},{value:'service',label:'Servis / Teknik'}]
watch(()=>props.modelValue,value=>{if(value){name.value='';type.value='facility';isActive.value=true}})
const close=()=>emit('update:modelValue',false)
const save=()=>{const value=name.value.trim();if(value)emit('save',{name:value,type:type.value,is_active:isActive.value})}
</script>
<template><div v-if="modelValue" class="fixed inset-0 z-[1000] flex items-center justify-center bg-gray-900/40 p-4 backdrop-blur-[2px]"><div class="w-full max-w-lg overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl dark:border-gray-800 dark:bg-gray-900"><div class="flex items-center justify-between border-b border-gray-200 px-5 py-4 dark:border-gray-800"><div><h2 class="text-base font-semibold text-gray-900 dark:text-white/90">Operasyonel Alan Ekle</h2><p class="mt-0.5 text-xs text-gray-500 dark:text-gray-400">Yeni operasyonel alanı tanımlayın.</p></div><button type="button" class="flex h-8 w-8 items-center justify-center rounded-lg text-gray-500 hover:bg-gray-100" @click="close"><X :size="18"/></button></div><div class="space-y-4 p-5"><label><span class="mb-1.5 block text-xs font-semibold text-gray-700 dark:text-gray-300">Operasyonel Alan</span><input v-model="name" type="text" placeholder="Operasyonel alan adı" class="h-11 w-full rounded-lg border border-gray-200 bg-white px-3 text-sm outline-none focus:border-brand-500"/></label><label><span class="mb-1.5 block text-xs font-semibold text-gray-700 dark:text-gray-300">Alan Tipi</span><select v-model="type" class="h-11 w-full rounded-lg border border-gray-200 bg-white px-3 text-sm outline-none focus:border-brand-500"><option v-for="item in types" :key="item.value" :value="item.value">{{item.label}}</option></select></label><label class="flex items-center gap-2 text-sm text-gray-700"><input v-model="isActive" type="checkbox" class="h-4 w-4 rounded border-gray-300"/> Aktif</label></div><div class="flex justify-end gap-2 border-t border-gray-200 px-5 py-4"><button type="button" class="h-10 rounded-lg border border-gray-200 px-4 text-sm font-semibold text-gray-600" @click="close">Vazgeç</button><button type="button" class="inline-flex h-10 items-center gap-2 rounded-lg bg-brand-500 px-5 text-sm font-semibold text-white disabled:opacity-50" :disabled="!name.trim()" @click="save"><Check :size="15"/> Kaydet</button></div></div></div></template>
