<script setup lang="ts">
import { Check, X } from 'lucide-vue-next'
import type { OperationalRegion } from '~/api/location'
const props=defineProps<{ modelValue:boolean; saving?:boolean; area?:OperationalRegion|null }>()
const emit=defineEmits<{ 'update:modelValue':[value:boolean]; save:[payload:{name:string;type:string;is_active:boolean}] }>()
const name=ref(''); const type=ref('facility'); const isActive=ref(true)
const types=[{value:'facility',label:'Tesis'},{value:'warehouse',label:'Depo'},{value:'business',label:'İşletme'},{value:'depot',label:'Dağıtım Merkezi'},{value:'office',label:'Ofis'},{value:'store',label:'Mağaza'}]
watch(()=>[props.modelValue,props.area] as const,([open,area])=>{if(open){name.value=area?.name||'';type.value=area?.type||'facility';isActive.value=area?.is_active??true}})
const close=()=>{if(!props.saving) emit('update:modelValue',false)}
const save=()=>{const value=name.value.trim();if(value&&!props.saving)emit('save',{name:value,type:type.value,is_active:isActive.value})}
</script>
<template><div v-if="modelValue" class="fixed inset-0 z-[1000] flex items-center justify-center bg-gray-900/40 p-4 backdrop-blur-[2px]"><div class="w-full max-w-lg overflow-hidden rounded-2xl border border-gray-200 bg-white shadow-2xl dark:border-gray-800 dark:bg-gray-900"><div class="flex items-center justify-between border-b border-gray-200 px-5 py-4 dark:border-gray-800"><div><h2 class="text-base font-semibold text-gray-900 dark:text-white/90">{{ area ? 'Operasyonel Alan Düzenle' : 'Operasyonel Alan Ekle' }}</h2><p class="mt-0.5 text-xs text-gray-500 dark:text-gray-400">{{ area ? 'Operasyonel alan bilgilerini düzenleyin.' : 'Yeni operasyonel alanı tanımlayın.' }}</p></div><button type="button" :disabled="saving" class="flex h-8 w-8 items-center justify-center rounded-lg text-gray-500 hover:bg-gray-100 disabled:opacity-50" @click="close"><X :size="18"/></button></div><div class="space-y-4 p-5"><label><span class="mb-1.5 block text-xs font-semibold text-gray-700 dark:text-gray-300">Operasyonel Alan</span><input v-model="name" type="text" placeholder="Operasyonel alan adı" class="mb-3 h-11 w-full rounded-lg border border-gray-200 bg-white px-3 text-sm outline-none focus:border-brand-500" :disabled="saving"/></label><label><span class="mb-3 block text-xs font-semibold text-gray-700 dark:text-gray-300">Alan Tipi</span><select v-model="type" class="h-11 w-full rounded-lg border border-gray-200 bg-white px-3 text-sm outline-none focus:border-brand-500" :disabled="saving"><option v-for="item in types" :key="item.value" :value="item.value">{{item.label}}</option></select></label><label class="mt-2 flex items-center gap-2.5 rounded-lg border border-gray-100 bg-gray-50/70 px-3 py-2.5 text-sm font-medium text-gray-700"><input v-model="isActive" type="checkbox" class="h-4 w-4 rounded border-gray-300" :disabled="saving"/> <span>Aktif</span></label></div><div class="flex justify-end gap-2 border-t border-gray-200 px-5 py-4"><button type="button" class="h-10 rounded-lg border border-gray-200 px-4 text-sm font-semibold text-gray-600 disabled:opacity-50" :disabled="saving" @click="close">Vazgeç</button><button type="button" class="inline-flex h-10 items-center gap-2 rounded-lg bg-brand-500 px-5 text-sm font-semibold text-white disabled:opacity-50" :disabled="!name.trim()||saving" @click="save"><span v-if="saving" class="h-4 w-4 animate-spin rounded-full border-2 border-white/40 border-t-white"></span><Check v-else :size="15"/> {{saving ? 'Kaydediliyor...' : area ? 'Güncelle' : 'Kaydet'}}</button></div></div></div></template>
