<script setup lang="ts">
import { ArrowLeft, Building2, ChevronRight, FileText, FolderTree, MapPin, Pencil, Users } from 'lucide-vue-next'
import { useOrganizationStore } from '~/stores/organization'

definePageMeta({ layout: 'default' })

const route = useRoute()
const router = useRouter()
const organizationStore = useOrganizationStore()
const tenantId = computed(() => Number(route.params.tenantId ?? 0))
const groupId = computed(() => Number(route.params.groupId ?? 0))

onMounted(async () => {
  if (!organizationStore.organizations.length) await organizationStore.fetchOrganizationsForTenant(tenantId.value)
})

const group = computed(() => organizationStore.organizations.find(item => item.id === groupId.value && item.type === 'group') ?? null)
const childOrganizations = computed(() => organizationStore.organizations.filter(item => item.parent_id === groupId.value))
const childGroups = computed(() => childOrganizations.value.filter(item => item.type === 'group'))
const companies = computed(() => childOrganizations.value.filter(item => item.type === 'company'))
const goBack = () => router.push(`/tenants/${tenantId.value}/organization/groups`)
</script>

<template>
  <div class="font-outfit">
    <div class="mx-auto w-full max-w-[1400px]">
      <div class="mb-5 flex items-center gap-2 text-xs text-gray-400"><button type="button" class="hover:text-brand-500" @click="goBack">Gruplar</button><ChevronRight :size="14" /><span class="font-medium text-gray-600 dark:text-gray-300">{{ group?.name || 'Grup' }}</span></div>
      <div v-if="group" class="mb-6 flex flex-col gap-4 rounded-xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03] sm:flex-row sm:items-center sm:justify-between"><div class="flex items-center gap-4"><div class="flex h-14 w-14 items-center justify-center rounded-xl bg-brand-50 text-brand-500 dark:bg-brand-500/10"><FolderTree :size="26" /></div><div><div class="flex items-center gap-2"><h1 class="text-2xl font-semibold text-gray-900 dark:text-white/90">{{ group.name }}</h1><span class="inline-flex items-center gap-1.5 rounded-full bg-success-50 px-2.5 py-1 text-xs font-medium text-success-600 dark:bg-success-500/15 dark:text-success-300"><span class="h-1.5 w-1.5 rounded-full bg-success-500" />{{ group.is_active === false || group.is_active === 0 ? 'Pasif' : 'Aktif' }}</span></div><p class="mt-1 text-sm text-gray-500 dark:text-gray-400">{{ group.description || 'Grup yönetim paneli' }}<span v-if="group.code"> · {{ group.code }}</span></p></div></div><div class="flex gap-2"><button type="button" class="inline-flex items-center gap-2 rounded-lg border border-gray-200 px-4 py-2.5 text-sm font-medium text-gray-600 hover:bg-gray-50 dark:border-gray-700 dark:text-gray-300 dark:hover:bg-white/5" @click="goBack"><ArrowLeft :size="16" />Gruplar</button></div></div>
      <div v-if="group" class="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-4"><div class="rounded-xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center justify-between"><p class="text-sm text-gray-500">Alt Gruplar</p><FolderTree :size="19" class="text-brand-500" /></div><p class="mt-3 text-2xl font-semibold text-gray-900 dark:text-white/90">{{ childGroups.length }}</p></div><div class="rounded-xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center justify-between"><p class="text-sm text-gray-500">Bağlı Şirketler</p><Building2 :size="19" class="text-brand-500" /></div><p class="mt-3 text-2xl font-semibold text-gray-900 dark:text-white/90">{{ companies.length }}</p></div><div class="rounded-xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center justify-between"><p class="text-sm text-gray-500">Operasyon</p><MapPin :size="19" class="text-brand-500" /></div><p class="mt-3 text-sm font-semibold text-gray-400">Henüz kullanılmıyor</p></div><div class="rounded-xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center justify-between"><p class="text-sm text-gray-500">Evraklar</p><FileText :size="19" class="text-brand-500" /></div><p class="mt-3 text-sm font-semibold text-gray-400">Henüz kullanılmıyor</p></div></div>
      <div v-if="group" class="mt-5 grid grid-cols-1 gap-5 xl:grid-cols-2"><section class="rounded-xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center justify-between"><div><h2 class="text-sm font-semibold text-gray-900 dark:text-white/90">Alt Organizasyonlar</h2><p class="mt-1 text-xs text-gray-500">Bu gruba doğrudan bağlı organizasyonlar.</p></div><FolderTree :size="19" class="text-gray-400" /></div><div v-if="childOrganizations.length" class="mt-5 space-y-2"><div v-for="item in childOrganizations" :key="item.id" class="flex items-center justify-between rounded-lg border border-gray-100 px-4 py-3 dark:border-gray-800"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-gray-50 text-gray-500 dark:bg-white/[0.04] dark:text-gray-400"><Building2 v-if="item.type === 'company'" :size="17" /><FolderTree v-else :size="17" /></span><div><p class="text-sm font-medium text-gray-800 dark:text-white/90">{{ item.name }}</p><p class="text-xs text-gray-500">{{ item.type === 'company' ? 'Şirket' : 'Grup' }}</p></div></div></div></div><div v-else class="mt-5 rounded-lg border border-dashed border-gray-200 px-4 py-8 text-center text-sm text-gray-400 dark:border-gray-800">Henüz alt organizasyon bulunmuyor.</div></section><section class="rounded-xl border border-gray-200 bg-white p-6 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center justify-between"><div><h2 class="text-sm font-semibold text-gray-900 dark:text-white/90">Grup Bilgileri</h2><p class="mt-1 text-xs text-gray-500">Temel organizasyon bilgileri.</p></div><Users :size="19" class="text-gray-400" /></div><dl class="mt-5 divide-y divide-gray-100 dark:divide-gray-800"><div class="flex justify-between gap-4 py-3"><dt class="text-sm text-gray-500">Slug</dt><dd class="text-sm font-medium text-gray-800 dark:text-gray-200">{{ group.slug || '—' }}</dd></div><div class="flex justify-between gap-4 py-3"><dt class="text-sm text-gray-500">Grup Kodu</dt><dd class="text-sm font-medium text-gray-800 dark:text-gray-200">{{ group.code || '—' }}</dd></div><div class="flex justify-between gap-4 py-3"><dt class="text-sm text-gray-500">Sıra</dt><dd class="text-sm font-medium text-gray-800 dark:text-gray-200">{{ group.display_order ?? 0 }}</dd></div></dl></section></div>
      <div v-else class="rounded-xl border border-gray-200 bg-white px-6 py-16 text-center shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><p class="text-sm font-medium text-gray-700 dark:text-gray-300">Grup bulunamadı.</p><button type="button" class="mt-4 inline-flex items-center gap-2 rounded-lg bg-brand-500 px-4 py-2.5 text-sm font-semibold text-white" @click="goBack"><ArrowLeft :size="16" />Gruplara Dön</button></div>
    </div>
  </div>
</template>