<script setup lang="ts">
import { ArrowLeft, Barcode, CalendarClock, CheckCircle2, FileText, FlaskConical, Truck, UserRound } from '@lucide/vue'
import { workRequests } from '~/data/operations'
const route = useRoute(); const tenantId = computed(() => String(route.params.tenantId)); const id = computed(() => String(route.params.requestId))
const item = computed(() => workRequests.find(x => x.id === id.value) ?? workRequests[0])
const approved = ref(item.value.status === 'Onaylandı' || item.value.status === 'Barkod Hazır')
const barcodeReady = ref(item.value.status === 'Barkod Hazır')
</script>
<template>
  <div class="mx-auto w-full max-w-[1200px] space-y-6">
    <div class="flex items-center gap-3"><NuxtLink :to="`/tenants/${tenantId}/work-requests`" class="text-gray-400 hover:text-gray-700"><ArrowLeft :size="19" /></NuxtLink><div><div class="text-xs font-medium text-gray-400">{{ item.id }}</div><h1 class="text-2xl font-semibold text-gray-900 dark:text-white/90">{{ item.title }}</h1></div><span class="ml-auto rounded-full bg-brand-50 px-3 py-1.5 text-xs font-medium text-brand-700">{{ item.status }}</span></div>
    <div class="grid gap-5 lg:grid-cols-[1fr_330px]">
      <div class="space-y-5"><div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><h2 class="mb-5 font-semibold">Talep ve Planlama</h2><div class="grid grid-cols-2 gap-5 text-sm"><div><p class="text-gray-400">Lokasyon</p><p class="mt-1 font-medium">{{ item.location }}</p></div><div><p class="text-gray-400">İşyeri</p><p class="mt-1 font-medium">{{ item.lbe }}</p></div><div><p class="text-gray-400">Taşeron</p><p class="mt-1 font-medium">{{ item.contractor }}</p></div><div><p class="text-gray-400">Planlanan</p><p class="mt-1 font-medium">{{ item.date }} · {{ item.time }}</p></div></div></div>
      <div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><div class="mb-5 flex items-center justify-between"><h2 class="font-semibold">İş Atamaları</h2><span class="text-xs text-gray-400">Onaydan sonra kesinleşir</span></div><div class="grid gap-3 sm:grid-cols-2"><div v-for="x in [{n:'Personel',v:item.people,i:UserRound},{n:'Evrak',v:item.documents,i:FileText},{n:'Araç',v:item.vehicles,i:Truck},{n:'Kimyasal',v:item.chemicals,i:FlaskConical}]" :key="x.n" class="rounded-xl border border-gray-100 p-4 dark:border-gray-800"><component :is="x.i" :size="17" class="text-brand-500"/><div class="mt-2 text-lg font-semibold">{{ x.v }}</div><div class="text-xs text-gray-400">{{ x.n }}</div></div></div></div></div>
      <aside class="space-y-5"><div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><h2 class="font-semibold">Süreç</h2><div class="mt-5 space-y-5"><div v-for="(step,i) in ['İş talebi oluşturuldu','Taşeron tarihi onayladı','Personel / araç / kimyasal atandı','Barkod oluşturuldu','Güvenlik kontrolü']" :key="step" class="flex gap-3"><div class="flex h-6 w-6 shrink-0 items-center justify-center rounded-full text-xs" :class="i < 2 || (i===2 && approved) || (i===3 && barcodeReady) ? 'bg-success-500 text-white' : 'bg-gray-100 text-gray-400 dark:bg-white/5'"><CheckCircle2 v-if="i < 2 || (i===2 && approved) || (i===3 && barcodeReady)" :size="15"/><span v-else>{{ i+1 }}</span></div><span class="text-sm">{{ step }}</span></div></div></div><div v-if="barcodeReady" class="rounded-2xl border border-brand-200 bg-brand-50 p-6 text-center dark:border-brand-500/20 dark:bg-brand-500/10"><Barcode class="mx-auto text-brand-500" :size="46"/><h3 class="mt-3 font-semibold">Barkod hazır</h3><p class="mt-1 text-xs text-gray-500">TSR-8A42K</p><button class="mt-4 rounded-xl bg-brand-500 px-4 py-2 text-sm font-medium text-white">Barkodu Görüntüle</button></div><button v-else @click="barcodeReady=true; approved=true" class="w-full rounded-xl bg-brand-500 px-4 py-3 text-sm font-medium text-white">Onayla ve Barkod Oluştur</button></aside>
    </div>
  </div>
</template>
