<script setup lang="ts">
import { ArrowLeft, CalendarDays, MapPin, ShieldCheck, Users } from '@lucide/vue'
const route = useRoute()
const tenantId = computed(() => String(route.params.tenantId))
const form = reactive({ title: '', location: 'Çerkezköy Fabrikası', lbe: 'Çerkezköy Fabrikası SGK', contractor: 'Tepe Güvenlik', date: '', time: '09:00', description: '' })
const submitted = ref(false)
const submit = () => { submitted.value = true }
</script>
<template>
  <div class="mx-auto w-full max-w-[1000px] space-y-6">
    <div class="flex items-center gap-3"><NuxtLink :to="`/tenants/${tenantId}/work-requests`" class="text-gray-400 hover:text-gray-700"><ArrowLeft :size="19" /></NuxtLink><div><h1 class="text-2xl font-semibold text-gray-900 dark:text-white/90">Yeni İş Talebi</h1><p class="mt-1 text-sm text-gray-500">İşin yapılacağı lokasyonu seçin, tarihi planlayın ve taşerona gönderin.</p></div></div>
    <div v-if="submitted" class="rounded-2xl border border-success-200 bg-success-50 p-4 text-sm text-success-700 dark:border-success-500/20 dark:bg-success-500/10 dark:text-success-400"><strong>Talep oluşturuldu.</strong> Taşeron planlanan tarihi görebilir ve onay ekranından tarih önerisi gönderebilir.</div>
    <form class="space-y-5" @submit.prevent="submit">
      <div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><h2 class="mb-5 font-semibold text-gray-900 dark:text-white">İş Talebi</h2><div class="grid gap-5 md:grid-cols-2"><label class="md:col-span-2"><span class="mb-2 block text-sm text-gray-600 dark:text-gray-300">İş başlığı</span><input v-model="form.title" required class="h-11 w-full rounded-xl border border-gray-200 px-3 text-sm dark:border-gray-700 dark:bg-gray-900" placeholder="Örn. Elektrik pano bakımı" /></label><label><span class="mb-2 block text-sm text-gray-600 dark:text-gray-300">Lokasyon</span><div class="relative"><MapPin class="absolute left-3 top-3 text-gray-400" :size="17" /><select v-model="form.location" class="h-11 w-full rounded-xl border border-gray-200 pl-10 text-sm dark:border-gray-700 dark:bg-gray-900"><option>Çerkezköy Fabrikası</option><option>Eskişehir Fabrikası</option><option>İstanbul Merkez</option></select></div></label><label><span class="mb-2 block text-sm text-gray-600 dark:text-gray-300">İşyeri</span><select v-model="form.lbe" class="h-11 w-full rounded-xl border border-gray-200 px-3 text-sm dark:border-gray-700 dark:bg-gray-900"><option>Çerkezköy Fabrikası SGK</option><option>Eskişehir Fabrikası SGK</option></select></label><label><span class="mb-2 block text-sm text-gray-600 dark:text-gray-300">Taşeron</span><select v-model="form.contractor" class="h-11 w-full rounded-xl border border-gray-200 px-3 text-sm dark:border-gray-700 dark:bg-gray-900"><option>Tepe Güvenlik</option><option>ABC Teknik</option></select></label><div><span class="mb-2 block text-sm text-gray-600 dark:text-gray-300">İş türü</span><div class="flex h-11 items-center gap-2 rounded-xl border border-gray-200 px-3 text-sm dark:border-gray-700"><ShieldCheck :size="16" class="text-brand-500" /> Geçici taşeron işi</div></div></div></div>
      <div class="rounded-2xl border border-gray-200 bg-white p-6 dark:border-gray-800 dark:bg-gray-900"><h2 class="mb-5 font-semibold text-gray-900 dark:text-white">Planlama</h2><div class="grid gap-5 md:grid-cols-2"><label><span class="mb-2 block text-sm text-gray-600 dark:text-gray-300">Önerilen tarih</span><div class="relative"><CalendarDays class="absolute left-3 top-3 text-gray-400" :size="17" /><input v-model="form.date" required type="date" class="h-11 w-full rounded-xl border border-gray-200 pl-10 text-sm dark:border-gray-700 dark:bg-gray-900" /></div></label><label><span class="mb-2 block text-sm text-gray-600 dark:text-gray-300">Önerilen saat</span><input v-model="form.time" type="time" class="h-11 w-full rounded-xl border border-gray-200 px-3 text-sm dark:border-gray-700 dark:bg-gray-900" /></label><label class="md:col-span-2"><span class="mb-2 block text-sm text-gray-600 dark:text-gray-300">İş açıklaması</span><textarea v-model="form.description" rows="4" class="w-full rounded-xl border border-gray-200 px-3 py-3 text-sm dark:border-gray-700 dark:bg-gray-900" placeholder="İşin kapsamı, giriş notları ve özel gereksinimler..."></textarea></label></div></div>
      <div class="flex justify-end gap-3"><NuxtLink :to="`/tenants/${tenantId}/work-requests`" class="rounded-xl border border-gray-200 px-5 py-2.5 text-sm font-medium dark:border-gray-700">Vazgeç</NuxtLink><button class="inline-flex items-center gap-2 rounded-xl bg-brand-500 px-5 py-2.5 text-sm font-medium text-white hover:bg-brand-600"><Users :size="16" /> Taşerona Gönder</button></div>
    </form>
  </div>
</template>
