<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { useRouter, useRoute } from 'vue-router'
import { Search, ShieldCheck, UserRound, MoreHorizontal, LockKeyhole, LoaderCircle, Check } from 'lucide-vue-next'
import { userAuthorizationApi, type AuthorizedUser, type AuthorizationPermission, type AuthorizationRole } from '~/api/user-authorization'

type UserStatus='Aktif'|'Pasif'
type User=AuthorizedUser & { role:string; scope:string; status:UserStatus; initials:string }
type PermissionGroup={name:string;items:Array<[string,string]>}
const users=ref<User[]>([]),roles=ref<AuthorizationRole[]>([]),permissions=ref<AuthorizationPermission[]>([])
const search=ref(''),activeView=ref<'users'|'roles'|'permissions'>('users'),selectedRole=ref(''),selectedPermissions=ref<string[]>([])
const selectedUser=ref<User|null>(null),showUserForm=ref(false),userRole=ref(''),userPermissions=ref<string[]>([])
const loading=ref(true),loadingUser=ref(false),savingRole=ref(false),savingPermissions=ref(false)
const {$toast}=useNuxtApp()
const router=useRouter()
const route=useRoute()
const roleMap=computed(()=>new Map(roles.value.map(role=>[role.name,role])))
const permissionGroups=computed<PermissionGroup[]>(()=>{
 const groups:Record<string,PermissionGroup>={
  'Kullanıcı Yönetimi':{name:'Kullanıcı Yönetimi',items:[]},Organizasyon:{name:'Organizasyon',items:[]},Lokasyon:{name:'Lokasyon',items:[]},Taşeron:{name:'Taşeron',items:[]},'Saha ve Evrak':{name:'Saha ve Evrak',items:[]},Raporlama:{name:'Raporlama',items:[]}}
 for(const p of permissions.value){const k=p.name,i:[string,string]=[k,k];if(k.startsWith('users.')||k.startsWith('roles.'))groups['Kullanıcı Yönetimi'].items.push(i);else if(k.startsWith('organizations.'))groups.Organizasyon.items.push(i);else if(k.startsWith('locations.'))groups.Lokasyon.items.push(i);else if(k.startsWith('contractor')||k.startsWith('personnel.')||k.startsWith('assets.'))groups.Taşeron.items.push(i);else if(k.startsWith('visits.')||k.startsWith('documents.')||k.startsWith('findings.'))groups['Saha ve Evrak'].items.push(i);else if(k.startsWith('reports.'))groups.Raporlama.items.push(i)}
 return Object.values(groups).filter(g=>g.items.length)
})
const roleName=(u:AuthorizedUser)=>u.roles?.[0]?.name??'-'
const roleLabel=(u:AuthorizedUser)=>roleMap.value.get(roleName(u))?.name??roleName(u)
const scopeLabel=(u:AuthorizedUser)=>{const s=u.scopes??[];if(!s.length)return'Tanımlanmamış';if(s.some(x=>x.scope_type==='tenant'))return'Tüm tenant';return s.map(x=>`${x.scope_type} #${x.scope_id}`).join(', ')}
const mapUser=(u:AuthorizedUser):User=>({...u,role:roleName(u),scope:scopeLabel(u),status:u.status===false||u.status===0||u.status==='0'||u.status==='pasif'||u.status==='Pasif'?'Pasif':'Aktif',initials:u.name.trim().split(/\s+/).filter(Boolean).slice(0,2).map(x=>x.charAt(0).toLocaleUpperCase('tr-TR')).join('')})
const filteredUsers=computed(()=>{const q=search.value.toLocaleLowerCase('tr-TR').trim();return users.value.filter(u=>!q||`${u.name} ${u.email} ${u.role} ${u.scope}`.toLocaleLowerCase('tr-TR').includes(q))})
const selectedRoleData=computed(()=>roles.value.find(r=>r.name===selectedRole.value)??roles.value[0])
const selectRole=(name:string)=>{selectedRole.value=name;selectedPermissions.value=[...(roles.value.find(r=>r.name===name)?.permissions?.map(p=>p.name)??[])]}
const togglePermission=(key:string)=>{selectedPermissions.value=selectedPermissions.value.includes(key)?selectedPermissions.value.filter(p=>p!==key):[...selectedPermissions.value,key]}
const openUserDetail=(u:User)=>{router.push(`/tenants/${route.params.tenantId}/users/${u.id}`)}
const loadAuthorization=async()=>{loading.value=true;try{const[u,r,p]=await Promise.all([userAuthorizationApi.listUsers(),userAuthorizationApi.listRoles(),userAuthorizationApi.listPermissions()]);users.value=u.map(mapUser);roles.value=r;permissions.value=p;if(r.length)selectRole(selectedRole.value&&r.some(x=>x.name===selectedRole.value)?selectedRole.value:r[0].name)}catch(e){console.error(e);$toast.error('Kullanıcı ve yetki bilgileri alınamadı.')}finally{loading.value=false}}
const saveRolePermissions=async()=>{if(!selectedRole.value||savingPermissions.value)return;savingPermissions.value=true;try{const updated=await userAuthorizationApi.syncRolePermissions(selectedRole.value,selectedPermissions.value);const i=roles.value.findIndex(r=>r.name===selectedRole.value);if(i>=0)roles.value[i]=updated;selectedPermissions.value=updated.permissions?.map(p=>p.name)??selectedPermissions.value;$toast.success('Rol yetkileri kaydedildi.')}catch(e){console.error(e);$toast.error('Rol yetkileri kaydedilemedi.')}finally{savingPermissions.value=false}}
const openUserAuthorization=async(u:User)=>{if(loadingUser.value||savingRole.value)return;selectedUser.value=u;userRole.value=u.roles?.[0]?.name??'';userPermissions.value=u.permissions?.map(p=>p.name)??[];showUserForm.value=true;loadingUser.value=true;try{const fresh=await userAuthorizationApi.getUser(u.id);selectedUser.value=mapUser(fresh);userRole.value=fresh.roles?.[0]?.name??'';userPermissions.value=fresh.permissions?.map(p=>p.name)??[]}catch(e){console.error(e);$toast.error('Kullanıcı yetkileri alınamadı.')}finally{loadingUser.value=false}}
const saveUserAuthorization=async()=>{if(!selectedUser.value||savingRole.value||loadingUser.value)return;savingRole.value=true;try{if(userRole.value)await userAuthorizationApi.assignRole(selectedUser.value.id,userRole.value);const updated=await userAuthorizationApi.syncPermissions(selectedUser.value.id,userPermissions.value);const i=users.value.findIndex(u=>u.id===selectedUser.value?.id);if(i>=0)users.value[i]=mapUser(updated);$toast.success('Kullanıcı yetkileri kaydedildi.');showUserForm.value=false}catch(e){console.error(e);$toast.error('Kullanıcı yetkileri kaydedilemedi.')}finally{savingRole.value=false}}
const closeUserAuthorization=()=>{if(!savingRole.value){showUserForm.value=false;selectedUser.value=null}}
onMounted(loadAuthorization)
</script>
<template>
<section class="space-y-5">
 <div class="flex flex-wrap items-center justify-between gap-3"><div><h1 class="text-xl font-semibold text-gray-900">Kullanıcılar</h1><p class="mt-1 text-sm text-gray-500">Kullanıcı, rol ve erişim yetkilerini yönetin.</p></div></div>
 <div class="flex gap-1 rounded-xl border border-gray-200 bg-white p-1"><button v-for="tab in [{key:'users',label:'Kullanıcılar',icon:UserRound},{key:'roles',label:'Roller',icon:ShieldCheck},{key:'permissions',label:'Permissions',icon:LockKeyhole}]" :key="tab.key" @click="activeView=tab.key as any" class="flex items-center gap-2 rounded-lg px-4 py-2 text-xs font-medium" :class="activeView===tab.key?'bg-brand-50 text-brand-600':'text-gray-500 hover:bg-gray-50'"><component :is="tab.icon" :size="15"/>{{tab.label}}</button></div>
 <div v-if="loading" class="flex min-h-[360px] items-center justify-center rounded-xl border border-gray-200 bg-white"><LoaderCircle :size="28" class="animate-spin text-brand-500"/></div>
 <template v-else-if="activeView==='users'">
  <div class="grid grid-cols-[repeat(3,minmax(0,1fr))] gap-3"><div class="min-w-0 rounded-xl border border-gray-200 bg-white p-4"><p class="text-xs text-gray-500">Toplam Kullanıcı</p><p class="mt-1 text-2xl font-semibold text-gray-900">{{users.length}}</p></div><div class="min-w-0 rounded-xl border border-gray-200 bg-white p-4"><p class="text-xs text-gray-500">Aktif</p><p class="mt-1 text-2xl font-semibold text-success-600">{{users.filter(u=>u.status==='Aktif').length}}</p></div><div class="min-w-0 rounded-xl border border-gray-200 bg-white p-4"><p class="text-xs text-gray-500">Rol Sayısı</p><p class="mt-1 text-2xl font-semibold text-brand-600">{{roles.length}}</p></div></div>
  <div class="overflow-hidden rounded-xl border border-gray-200 bg-white"><div class="border-b border-gray-100 p-4"><div class="relative max-w-md"><Search :size="15" class="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400"/><input v-model="search" class="h-9 w-full rounded-lg border border-gray-200 bg-gray-50 pl-9 pr-3 text-xs outline-none" placeholder="Kullanıcı ara..."/></div></div><div class="overflow-x-auto"><table class="w-full min-w-[800px] text-left"><thead class="bg-gray-50/70 text-xs text-gray-500"><tr><th class="px-5 py-3">Kullanıcı</th><th class="px-4 py-3">Rol</th><th class="px-4 py-3">Erişim Alanı</th><th class="px-4 py-3">Durum</th><th class="w-12"></th></tr></thead><tbody><tr v-for="u in filteredUsers" :key="u.id" @click="openUserDetail(u)" class="cursor-pointer border-t border-gray-100 hover:bg-gray-50"><td class="px-5 py-4"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-full bg-brand-50 text-xs font-semibold text-brand-600">{{u.initials}}</span><div><p class="text-sm font-medium text-gray-800">{{u.name}}</p><p class="text-[11px] text-gray-400">{{u.email}}</p></div></div></td><td class="px-4 py-4"><span class="rounded-md bg-gray-100 px-2 py-1 text-[11px] font-medium text-gray-600">{{roleLabel(u)}}</span></td><td class="px-4 py-4 text-xs text-gray-600">{{u.scope}}</td><td class="px-4 py-4"><span class="rounded-full px-2.5 py-1 text-[11px] font-medium" :class="u.status==='Aktif'?'bg-success-50 text-success-600':'bg-gray-100 text-gray-500'">{{u.status}}</span></td><td class="px-4"><button @click.stop="openUserAuthorization(u)" class="text-gray-400 hover:text-gray-700"><MoreHorizontal :size="17"/></button></td></tr></tbody></table></div></div>
 </template>
 <template v-else-if="activeView==='roles'"><div class="grid grid-cols-1 gap-4 lg:grid-cols-2"><div v-for="role in roles" :key="role.id" class="rounded-xl border border-gray-200 bg-white p-5"><div class="flex items-start justify-between"><div><div class="flex items-center gap-2"><ShieldCheck :size="17" class="text-brand-600"/><h3 class="text-sm font-semibold text-gray-900">{{role.name}}</h3></div><p class="mt-2 text-xs leading-5 text-gray-500">{{role.permissions?.length??0}} yetki tanımlı.</p></div><span class="rounded-md bg-gray-100 px-2 py-1 text-[10px] font-medium text-gray-500">{{role.guard_name??'web'}}</span></div><div class="mt-4 flex flex-wrap gap-1.5"><span v-for="p in role.permissions" :key="p.id" class="rounded-md border border-gray-100 bg-gray-50 px-2 py-1 text-[10px] text-gray-600">{{p.name}}</span></div><button @click="selectRole(role.name);activeView='permissions'" class="mt-4 text-xs font-medium text-brand-600 hover:underline">Yetkileri düzenle →</button></div></div></template>
 <template v-else><div class="grid grid-cols-1 gap-5 lg:grid-cols-[260px_1fr]"><div class="rounded-xl border border-gray-200 bg-white p-3"><p class="px-2 py-2 text-xs font-semibold text-gray-700">Roller</p><button v-for="role in roles" :key="role.id" @click="selectRole(role.name)" class="mb-1 w-full rounded-lg px-3 py-2.5 text-left" :class="selectedRole===role.name?'bg-brand-50':'hover:bg-gray-50'"><p class="text-xs font-medium" :class="selectedRole===role.name?'text-brand-600':'text-gray-700'">{{role.name}}</p><p class="mt-0.5 text-[10px] text-gray-400">{{role.permissions?.length??0}} yetki</p></button></div><div class="rounded-xl border border-gray-200 bg-white p-5"><div class="mb-5 flex items-center justify-between"><div><h2 class="text-sm font-semibold text-gray-900">{{selectedRoleData?.name}} · Permissions</h2><p class="mt-1 text-xs text-gray-500">Bu rolün sahip olduğu yetkileri belirleyin.</p></div><span class="rounded-md bg-brand-50 px-2.5 py-1 text-[11px] font-medium text-brand-600">{{selectedPermissions.length}} yetki</span></div><div class="space-y-4"><div v-for="group in permissionGroups" :key="group.name"><h3 class="mb-2 text-xs font-semibold text-gray-700">{{group.name}}</h3><div class="divide-y divide-gray-100 rounded-lg border border-gray-100"><label v-for="item in group.items" :key="item[0]" class="flex cursor-pointer items-center justify-between px-3 py-3 hover:bg-gray-50"><span><span class="block text-xs font-medium text-gray-700">{{item[1]}}</span><span class="text-[10px] text-gray-400">{{item[0]}}</span></span><input type="checkbox" :checked="selectedPermissions.includes(item[0])" @change="togglePermission(item[0])" class="h-4 w-4 rounded border-gray-300 text-brand-600"/></label></div></div></div><div class="mt-5 flex justify-end"><button :disabled="savingPermissions||!selectedRole" @click="saveRolePermissions" class="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2 text-xs font-medium text-white disabled:opacity-60"><LoaderCircle v-if="savingPermissions" :size="14" class="animate-spin"/><Check v-else :size="14"/>{{savingPermissions?'Kaydediliyor...':'Yetkileri Kaydet'}}</button></div></div></div></template>
 <div v-if="showUserForm" class="fixed inset-0 z-50 flex items-center justify-center bg-black/30 p-4" @click.self="closeUserAuthorization"><div class="w-full max-w-lg rounded-xl bg-white p-6 shadow-xl"><h2 class="text-base font-semibold text-gray-900">Kullanıcı Yetkileri</h2><p class="mt-1 text-xs text-gray-500">{{selectedUser?.name}}</p><div v-if="loadingUser" class="flex min-h-[240px] items-center justify-center"><LoaderCircle :size="24" class="animate-spin text-brand-500"/></div><template v-else><div class="mt-5"><label class="mb-2 block text-xs font-medium text-gray-700">Rol</label><select v-model="userRole" class="h-10 w-full rounded-lg border border-gray-200 bg-white px-3 text-xs outline-none"><option value="">Rol seçin</option><option v-for="role in roles" :key="role.id" :value="role.name">{{role.name}}</option></select></div><div class="mt-5 max-h-[280px] space-y-3 overflow-y-auto"><div v-for="group in permissionGroups" :key="group.name"><h3 class="mb-2 text-xs font-semibold text-gray-700">{{group.name}}</h3><div class="divide-y divide-gray-100 rounded-lg border border-gray-100"><label v-for="item in group.items" :key="item[0]" class="flex cursor-pointer items-center justify-between px-3 py-2.5 hover:bg-gray-50"><span class="text-xs text-gray-700">{{item[1]}}</span><input type="checkbox" :checked="userPermissions.includes(item[0])" @change="userPermissions=userPermissions.includes(item[0])?userPermissions.filter(p=>p!==item[0]):[...userPermissions,item[0]]" class="h-4 w-4 rounded border-gray-300 text-brand-600"/></label></div></div></div><div class="mt-5 flex justify-end gap-2"><button @click="closeUserAuthorization" class="rounded-lg border border-gray-200 px-4 py-2 text-xs text-gray-600">Vazgeç</button><button :disabled="savingRole||loadingUser" @click="saveUserAuthorization" class="inline-flex items-center gap-2 rounded-lg bg-brand-600 px-4 py-2 text-xs font-medium text-white disabled:opacity-60"><LoaderCircle v-if="savingRole" :size="14" class="animate-spin"/><Check v-else :size="14"/>{{savingRole?'Kaydediliyor...':'Kaydet'}}</button></div></template></div></div>
</section>
</template>
