<script setup lang="ts">
import { ArrowLeft, CalendarDays, MapPin, Users, ClipboardCheck } from 'lucide-vue-next'

definePageMeta({ layout: 'default' })
const route = useRoute()
const tenantId = computed(() => String(route.params.tenantId ?? '1'))
const contractorId = computed(() => String(route.params.contractorId ?? ''))
const contractor = { name: 'ABC Teknik Bakım Hizmetleri Ltd. Şti.', shortName: 'ABC Teknik', type: 'Geçici', status: 'Aktif' }
const visits = [
  { date: '18.08.2026', location: 'Beylikdüzü Kampüsü', business: 'Arçelik A.Ş.', purpose: 'Forklift bakım ve teknik servis', people: 3, status: 'Tamamlandı' },
  { date: '04.07.2026', location: 'Çayırova Fabrikası', business: 'Arçelik A.Ş.', purpose: 'Periyodik bakım', people: 2, status: 'Tamamlandı' },
  { date: '22.05.2026', location: 'Sütlüce Kampüsü', business: 'Arçelik Pazarlama A.Ş.', purpose: 'Acil teknik müdahale', people: 4, status: 'Tamamlandı' },
  { date: '11.03.2026', location: 'Beylikdüzü Kampüsü', business: 'Arçelik A.Ş.', purpose: 'Makine arıza müdahalesi', people: 2, status: 'Tamamlandı' }
]
</script>
<template>
  <div class="font-outfit mx-auto w-full max-w-[1400px]">
    <div class="mb-6 flex items-start gap-4">
      <NuxtLink :to="`/tenants/${tenantId}/contractors/${contractorId}`" class="mt-1 flex h-9 w-9 shrink-0 items-center justify-center rounded-lg border border-gray-200 bg-white text-gray-500 hover:bg-gray-50 dark:border-gray-800 dark:bg-white/[0.03]"><ArrowLeft :size="17" /></NuxtLink>
      <div><div class="flex flex-wrap items-center gap-2"><h1 class="text-2xl font-semibold tracking-tight text-gray-900 dark:text-white/90">Saha Geçmişi</h1><span class="rounded-full bg-amber-50 px-2.5 py-1 text-xs font-medium text-amber-600">Geçici</span></div><p class="mt-1.5 text-sm text-gray-500 dark:text-gray-400">{{ contractor.name }} firmasının lokasyon ve saha ziyaret geçmişi.</p></div>
    </div>
    <section class="mb-5 rounded-xl border border-gray-200 bg-white p-5 shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center gap-4"><div class="flex h-12 w-12 items-center justify-center rounded-full bg-brand-50 text-sm font-bold text-brand-600 dark:bg-brand-500/10">AT</div><div><h2 class="text-base font-semibold text-gray-900 dark:text-white/90">{{ contractor.shortName }}</h2><p class="mt-1 text-xs text-gray-500">{{ contractor.name }}</p></div><div class="ml-auto rounded-full bg-success-50 px-2.5 py-1 text-xs font-medium text-success-600 dark:bg-success-500/10">{{ contractor.status }}</div></div></section>
    <div class="mb-5 grid grid-cols-1 gap-4 md:grid-cols-3"><div class="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-brand-50 text-brand-600 dark:bg-brand-500/10"><MapPin :size="17" /></span><div><p class="text-xs text-gray-500">Ziyaret Edilen Lokasyon</p><p class="mt-1 text-lg font-semibold text-gray-800 dark:text-white/90">3</p></div></div></div><div class="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-amber-50 text-amber-600"><CalendarDays :size="17" /></span><div><p class="text-xs text-gray-500">2026 Ziyareti</p><p class="mt-1 text-lg font-semibold text-gray-800 dark:text-white/90">4</p></div></div></div><div class="rounded-xl border border-gray-200 bg-white p-5 dark:border-gray-800 dark:bg-white/[0.03]"><div class="flex items-center gap-3"><span class="flex h-9 w-9 items-center justify-center rounded-lg bg-success-50 text-success-600 dark:bg-success-500/10"><Users :size="17" /></span><div><p class="text-xs text-gray-500">Sahaya Gelen Personel</p><p class="mt-1 text-lg font-semibold text-gray-800 dark:text-white/90">11</p></div></div></div></div>
    <section class="overflow-hidden rounded-xl border border-gray-200 bg-white shadow-theme-xs dark:border-gray-800 dark:bg-white/[0.03]"><div class="border-b border-gray-100 px-5 py-4 dark:border-gray-800"><h2 class="text-sm font-semibold text-gray-900 dark:text-white/90">Lokasyon & Saha Ziyaretleri</h2><p class="mt-1 text-xs text-gray-500">Geçici alt yüklenicinin tenant içerisindeki fiili saha geçmişi.</p></div><div class="overflow-x-auto"><table class="w-full min-w-[850px] text-left"><thead class="border-b border-gray-100 bg-gray-50/70 dark:border-gray-800 dark:bg-gray-900/50"><tr><th class="px-5 py-3 text-xs font-medium text-gray-500">Tarih</th><th class="px-5 py-3 text-xs font-medium text-gray-500">Lokasyon</th><th class="px-5 py-3 text-xs font-medium text-gray-500">Ana Firma</th><th class="px-5 py-3 text-xs font-medium text-gray-500">Ziyaret Nedeni</th><th class="px-5 py-3 text-xs font-medium text-gray-500">Personel</th><th class="px-5 py-3 text-xs font-medium text-gray-500">Durum</th></tr></thead><tbody class="divide-y divide-gray-100 dark:divide-gray-800"><tr v-for="visit in visits" :key="`${visit.date}-${visit.location}`" class="hover:bg-gray-50/70 dark:hover:bg-white/[0.02]"><td class="px-5 py-4 text-sm font-medium text-gray-800 dark:text-white/90">{{ visit.date }}</td><td class="px-5 py-4"><div class="flex items-center gap-2"><MapPin :size="15" class="text-gray-400"/><div><p class="text-sm font-medium text-gray-800 dark:text-white/90">{{ visit.location }}</p><p class="text-xs text-gray-500">{{ visit.business }}</p></div></div></td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ visit.business }}</td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ visit.purpose }}</td><td class="px-5 py-4 text-sm text-gray-600 dark:text-gray-300">{{ visit.people }}</td><td class="px-5 py-4"><span class="inline-flex items-center gap-1.5 rounded-full bg-success-50 px-2.5 py-1 text-xs font-medium text-success-600 dark:bg-success-500/10"><ClipboardCheck :size="13"/> {{ visit.status }}</span></td></tr></tbody></table></div></section>
  </div>
</template>
