<script setup lang="ts">
import { Plus } from "lucide-vue-next";
import { locationApi, type LocationApiItem, type LocationBusinessEntity, type LocationOrganizationContractor, type OperationalRegion } from "~/api/location";
import ContractorCreateModal from "./components/ContractorCreateModal.vue";
import LocationCompaniesTab from "./components/LocationCompaniesTab.vue";
import LocationContractorsTab from "./components/LocationContractorsTab.vue";
import LocationOperationalAreasTab from "./components/LocationOperationalAreasTab.vue";
import LocationDetailCard from "./components/LocationDetailCard.vue";
import { companies as mockCompanies, areas as mockAreas, type DangerClass, type Company, type Contractor } from "~/data/location-detail.mock";
definePageMeta({ layout: "default" });
const route=useRoute(); const locationId=computed(()=>Number(route.params.locationId??1)); const {setScope}=useOrganizationScope(); const {$toast}=useNuxtApp(); const runtimeConfig=useRuntimeConfig(); const location=ref<LocationApiItem|null>(null); const locationLoading=ref(true); const locationError=ref("");
const assetUrl=(path:string|null|undefined)=>{if(!path)return"";if(/^https?:\/\//i.test(path))return path;return new URL(`/storage${path.startsWith("/")?path:`/${path}`}`,runtimeConfig.public.apiBaseUrl).toString()};
const locationView=computed(()=>({id:locationId.value,name:location.value?.name??"",city:location.value?.city?.name??"",district:location.value?.district?.name??"",address:location.value?.address??"",image:assetUrl(location.value?.image),status:location.value?.is_active===false?("passive" as const):("active" as const)}));
const loadLocation=async()=>{locationLoading.value=true;locationError.value="";try{location.value=await locationApi.get("",locationId.value)}catch(error){locationError.value=error instanceof Error?error.message:"Lokasyon bilgileri alınamadı."}finally{locationLoading.value=false}};
const activeTab=ref<"companies"|"contractors"|"areas">("companies"); const locationTabs=[{label:"Firmalar",key:"companies"},{label:"Alt Yükleniciler",key:"contractors"},{label:"Operasyonel Alanlar",key:"areas"}];
const showContractorModal=ref(false); const editingContractor=ref<Contractor|null>(null); const contractorModalLoading=ref(false); const contractorSaving=ref(false); const companies=ref<Company[]>(mockCompanies); const contractors=ref<Contractor[]>([]); const contractorPool=ref<LocationOrganizationContractor[]>([]); const attachedBusinessEntities=ref<LocationBusinessEntity[]>([]); const areas=ref(mockAreas); const contractorAreas=ref<OperationalRegion[]>([]); const operationalAreasTab=ref<InstanceType<typeof LocationOperationalAreasTab>|null>(null); const companiesTab=ref<InstanceType<typeof LocationCompaniesTab>|null>(null);
const loadContractorData=async()=>{try{const[pool,attached,operationalRegions]=await Promise.all([locationApi.organizationContractors(locationId.value),locationApi.businessEntities(locationId.value),locationApi.operationalRegions(locationId.value)]); contractorPool.value=pool.filter(x=>x.contractor_type==="permanent"); attachedBusinessEntities.value=attached.filter(x=>x.type==="contractor"); contractors.value=attachedBusinessEntities.value.map(entity=>{const poolItem=contractorPool.value.find(x=>x.business_entity_id===entity.id);const pivot=entity.pivot??{};return{id:entity.id,name:entity.name,logo:assetUrl(poolItem?.logo_path),operationalArea:contractorAreas.value.find(x=>x.id===pivot.operational_region_id)?.name||"Tüm Tesis",activity:pivot.activity||"",subActivity:pivot.sub_activity||"",nace:pivot.nace_code||"",dangerClass:(pivot.hazard_class||"") as DangerClass,sgk:pivot.sgk_workplace_number||"",status:poolItem?.status==="passive"?"passive":"active",contractorType:"Daimi",businessEntityId:entity.id}})}catch(error){locationError.value=error instanceof Error?error.message:"Alt yükleniciler alınamadı."}};
const availableContractors=computed(()=>{const attachedIds=new Set(attachedBusinessEntities.value.map(x=>x.id));return contractorPool.value.filter(x=>!attachedIds.has(x.business_entity_id)).map(x=>({businessEntityId:x.business_entity_id,name:x.name,logo:assetUrl(x.logo_path)}))});
const openAddContractor=()=>{editingContractor.value=null;showContractorModal.value=true};
const openEditContractor=async(contractor:Contractor)=>{editingContractor.value={...contractor};contractorModalLoading.value=true;showContractorModal.value=true;await nextTick();contractorModalLoading.value=false};
const closeContractorModal=()=>{if(contractorSaving.value)return;showContractorModal.value=false;editingContractor.value=null};
const saveContractor=async(p:{businessEntityId:number;areaId:number|null;activity:string;subActivity:string;nace:string;dangerClass:string;sgk:string})=>{if(contractorSaving.value)return;contractorSaving.value=true;try{const payload={operational_region_id:p.areaId,activity:p.activity,sub_activity:p.subActivity,nace_code:p.nace,hazard_class:p.dangerClass,sgk_workplace_number:p.sgk};if(editingContractor.value?.businessEntityId===p.businessEntityId){await locationApi.updateBusinessEntity(locationId.value,p.businessEntityId,payload);$toast.success("Alt yüklenici bilgileri güncellendi.")}else{await locationApi.createBusinessEntity(locationId.value,{business_entity_id:p.businessEntityId,...payload});$toast.success("Alt yüklenici lokasyona başarıyla bağlandı.")}await loadContractorData();showContractorModal.value=false;editingContractor.value=null}catch(error){$toast.error(error instanceof Error?error.message:"Alt yüklenici bilgileri kaydedilemedi.")}finally{contractorSaving.value=false}};
const removeContractor=async(businessEntityId:number)=>{try{await locationApi.removeBusinessEntity(locationId.value,businessEntityId);await loadContractorData();$toast.success("Alt yüklenici lokasyondan çıkarıldı")}catch(error){$toast.error(error instanceof Error?error.message:"Alt yüklenici lokasyondan çıkarılamadı")}};
onMounted(async()=>{await loadLocation();if(location.value){setScope("location",{id:location.value.id,name:location.value.name,description:"Tesis",icon:undefined});await loadContractorData()}});
</script>
<template><div class="font-outfit mx-auto w-full max-w-[1400px] location-detail-refinement"><LocationDetailCard :location="locationView"/><div v-if="locationError" class="mt-3 rounded-lg border border-error-200 bg-error-50 px-4 py-3 text-sm text-error-600">{{locationError}}</div><OrganizationTabs v-model="activeTab" :tabs="locationTabs"/><div class="mb-4 flex items-center justify-end"><button v-if="activeTab==='companies'" class="inline-flex h-10 items-center gap-2 rounded-lg bg-brand-500 px-4 text-sm font-semibold text-white" @click="companiesTab?.openCreate()"><Plus :size="16"/> Firma Ekle</button><button v-else-if="activeTab==='contractors'" class="inline-flex h-10 items-center gap-2 rounded-lg bg-brand-500 px-4 py-2 text-sm font-semibold text-white" @click="openAddContractor"><Plus :size="16"/> Alt Yüklenici Ekle</button><button v-else class="inline-flex h-10 items-center gap-2 rounded-lg bg-brand-500 px-4 text-sm font-semibold text-white" @click="operationalAreasTab?.openCreate()"><Plus :size="16"/> Operasyonel Alan Ekle</button></div><LocationCompaniesTab v-if="activeTab==='companies'" ref="companiesTab" :companies="companies" :areas="areas"/><LocationContractorsTab v-else-if="activeTab==='contractors'" :contractors="contractors" @remove="removeContractor" @edit="openEditContractor"/><LocationOperationalAreasTab v-else ref="operationalAreasTab" :location-id="locationId"/><ContractorCreateModal v-model="showContractorModal" :contractors="availableContractors" :areas="contractorAreas" :edit-value="editingContractor" :loading="contractorModalLoading" :saving="contractorSaving" @save="saveContractor" @update:model-value="value=>{if(!value)closeContractorModal()}"/></div></template>
